### Cadastrar uma folha
POST https://localhost:5001/api/folhapagamento/cadastrar
Content-Type: application/json

{
    "funcionarioid" : 1,
    "valorhora" : 50,    
    "quantidadehoras" : 100,
    "salariobruto" : 5000,
    "impostorenda" : 505.64,
    "impostoinss" : 550.00,
    "impostofgts" : 400,
    "salarioliquido" : 3944.36
}

### Listar a folha
GET https://localhost:5001/api/folha/listar

### Buscar/{cpf}/{mês}/{ano} folha
GET https://localhost:5001/api/folha/buscar

### Filtrar/{mês}/{ano} folha
GET https://localhost:5001/api/folha/filtrar